print("Calculation for the amount of paint that a cuboid room needs:")
Nheight = input("Enter height in metres ")
print(Nheight)
Nlength = input("Enter length in metres ")
print(Nlength)
Nwidth = input("Enter width in metres ")
print(Nwidth)
NPaintNeeded = ((Nheight*Nlength)*2) + ((Nheight*Nwidth)*2) + (Nwidth*Nlength)
print(NPaintNeeded) 
